// export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const LIKE_RESTAURANT = 'LIKE_RESTAURANT';
export const SELECTED_RESTAURANT = 'SELECTED_RESTAURANT';
export const REMOVE_SELECTED_RESTAURANT = 'REMOVE_SELECTED_RESTAURANT'
export const INCREASE_COUNTER = 'INCREASE_COUNTER';