export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS'
export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE'
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS'
export const MAKE_CURRENT_RESTAURANT = 'MAKE_CURRENT_RESTAURANT'